-- NOTE: This file is auto generated by ./sql-generator

-- AlbumContainerRepository.getById
select
  *
from
  "album_container"
where
  "id" = $1

-- AlbumContainerRepository.create
begin
insert into
  "album_container" ("ownerId", "name", "parentId")
values
  ($1, $2, $3)
returning
  *
rollback

-- AlbumContainerRepository.move
begin
delete from "album_container_closure"
where
  "id_descendant" in (
    select
      "id_descendant"
    from
      "album_container_closure"
    where
      "id_ancestor" = $1
  )
  and "id_ancestor" not in (
    select
      "id_descendant"
    from
      "album_container_closure"
    where
      "id_ancestor" = $2
  )
update "album_container"
set
  "parentId" = $1
where
  "id" = $2
returning
  *
rollback

-- AlbumContainerRepository.delete
delete from "album_container"
where
  "id" = $1

-- AlbumContainerRepository.getForUser
select
  "album_container".*
from
  "album_container"
where
  (
    "album_container"."ownerId" = $1
    or exists (
      select
      from
        "album_container_user"
        inner join "album_container_closure" on "album_container_closure"."id_ancestor" = "album_container_user"."albumContainerId"
      where
        "album_container_closure"."id_descendant" = "album_container"."id"
        and "album_container_user"."userId" = $2
    )
  )
  and "album_container"."deletedAt" is null
order by
  "album_container"."name" asc

-- AlbumContainerRepository.hasAccess
select
  "album_container"."id"
from
  "album_container"
where
  "album_container"."id" = $1
  and "album_container"."deletedAt" is null
  and (
    "album_container"."ownerId" = $2
    or exists (
      select
      from
        "album_container_user"
        inner join "album_container_closure" on "album_container_closure"."id_ancestor" = "album_container_user"."albumContainerId"
      where
        "album_container_closure"."id_descendant" = "album_container"."id"
        and "album_container_user"."userId" = $3
    )
  )

-- AlbumContainerRepository.isDescendantOf
select
  "depth"
from
  "album_container_closure"
where
  "id_ancestor" = $1
  and "id_descendant" = $2
  and "depth" > $3

-- AlbumContainerRepository.getDepth
select
  max("depth") as "maxDepth"
from
  "album_container_closure"
where
  "id_descendant" = $1

-- AlbumContainerRepository.getHeight
select
  max("depth") as "maxDepth"
from
  "album_container_closure"
where
  "id_ancestor" = $1

-- AlbumContainerRepository.rename
update "album_container"
set
  "name" = $1
where
  "id" = $2
returning
  *

-- AlbumContainerRepository.getUser
select
  *
from
  "album_container_user"
where
  "albumContainerId" = $1
  and "userId" = $2

-- AlbumContainerRepository.addUser
insert into
  "album_container_user" ("albumContainerId", "userId", "role")
values
  ($1, $2, $3)
returning
  *

-- AlbumContainerRepository.removeUser
delete from "album_container_user"
where
  "albumContainerId" = $1
  and "userId" = $2

-- AlbumContainerRepository.updateUserRole
update "album_container_user"
set
  "role" = $1
where
  "albumContainerId" = $2
  and "userId" = $3
returning
  *

-- AlbumContainerRepository.getThumbnailAssetIdsForContainers
select
  "closure"."id_ancestor" as "containerId",
  "asset"."id" as "assetId",
  "asset"."fileCreatedAt" as "fileCreatedAt"
from
  "album_container_closure" as "closure"
  inner join "album" on "album"."containerId" = "closure"."id_descendant"
  inner join "album_asset" on "album_asset"."albumId" = "album"."id"
  inner join "asset" on "asset"."id" = "album_asset"."assetId"
where
  "closure"."id_ancestor" in ($1)
  and "album"."deletedAt" is null
  and "asset"."deletedAt" is null
  and not "album"."id" = any ($2::uuid[])
order by
  "fileCreatedAt" desc
select
  "closure"."id_ancestor" as "containerId",
  "asset"."id" as "assetId",
  "asset"."fileCreatedAt" as "fileCreatedAt"
from
  "album_container_closure" as "closure"
  inner join "album" on "album"."containerId" = "closure"."id_descendant"
  inner join "asset" on "asset"."id" = "album"."cachedThumbnailAssetId"
where
  "closure"."id_ancestor" in ($1)
  and "album"."kind" = 'smart'
  and "album"."deletedAt" is null
  and "asset"."deletedAt" is null
  and not "album"."id" = any ($2::uuid[])

-- AlbumContainerRepository.getSmartAlbumsForContainers
select distinct
  on ("album"."id") "album"."id",
  "album"."filter",
  "album"."cacheComputedAt",
  "album"."cacheInvalidatedAt",
  "owner"."userId" as "ownerId"
from
  "album_container_closure" as "closure"
  inner join "album" on "album"."containerId" = "closure"."id_descendant"
  inner join "album_user" as "owner" on "owner"."albumId" = "album"."id"
  and "owner"."role" = 'owner'
where
  "closure"."id_ancestor" in ($1)
  and "album"."kind" = 'smart'
  and "album"."deletedAt" is null

-- AlbumContainerRepository.getUsersForContainers
select
  "album_container_user"."albumContainerId" as "albumContainerId",
  "album_container_user"."userId" as "userId",
  "album_container_user"."role" as "role",
  "user"."id" as "user_id",
  "user"."name" as "user_name",
  "user"."email" as "user_email",
  "user"."avatarColor" as "user_avatarColor",
  "user"."profileImagePath" as "user_profileImagePath",
  "user"."profileChangedAt" as "user_profileChangedAt"
from
  "album_container_user"
  inner join "user" on "user"."id" = "album_container_user"."userId"
where
  "album_container_user"."albumContainerId" in ($1)
  and "user"."deletedAt" is null
order by
  "user"."name" asc
