-- NOTE: This file is auto generated by ./sql-generator

-- LockRepository.lockAlbum
insert into
  "locked_album" ("userId", "albumId")
values
  ($1, $2)
on conflict do nothing

-- LockRepository.unlockAlbum
delete from "locked_album"
where
  "userId" = $1
  and "albumId" = $2

-- LockRepository.lockContainer
insert into
  "locked_container" ("userId", "containerId")
values
  ($1, $2)
on conflict do nothing

-- LockRepository.unlockContainer
delete from "locked_container"
where
  "userId" = $1
  and "containerId" = $2

-- LockRepository.getLocks
select
  "albumId"
from
  "locked_album"
where
  "userId" = $1
select
  "containerId"
from
  "locked_container"
where
  "userId" = $1
